name: Build firmware

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v3
      - name: Prepare Env
        run: | 
            sudo apt update
            sudo apt install yui-compressor libxml2-utils flex 
            wget -q https://github.com/roleoroleo/sonoff-hack/releases/download/toolchain-0.0.1/arm-sonoff-linux-uclibcgnueabi.tgz
            tar xf arm-sonoff-linux-uclibcgnueabi.tgz && rm -rf arm-sonoff-linux-uclibcgnueabi.tgz
            echo "${GITHUB_WORKSPACE}/arm-sonoff-linux-uclibcgnueabi/bin" >> $GITHUB_PATH
            git submodule update --init
      
      - name: Build Submodules
        run: |    
            bash -x ./scripts/compile_ci_pre.sh

      - name: Build stuff
        run: |    
            bash -x ./scripts/compile_ci_post.sh

      - name: Pack stuff
        run: |    
            bash -x ./scripts/pack_fw.all.sh
            ls -l out/*
            ls -la
            pwd           
            
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Firmware Builds
          path: out/**/**.tgz
